language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=deer
    - THEANO_VERSION="0.7"
    - NUMPY_VERSION="1.10"
    - SCIPY_VERSION="0.17"
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.5"
    - PYTHON_VERSION="2.7" EXAMPLE="toy_env"
    - PYTHON_VERSION="3.5" EXAMPLE="toy_env"

install: source ci_scripts/install.sh
script: bash ci_scripts/test.sh
after_success: source ci_scripts/success.sh

